### ISSUE TITLE
能不能標記一下每個項目最後更新時間？

### ISSUE THREAD

**Issue by 8884361** [bangumi-users/awesome-bangumi#3]
不用太及時，每個月輪詢一下就好了。
另外，部分項目找不到編譯後的下載點(沒有成品的話最起碼有源碼可以自己編譯啊)

**Comment by 8884361** [comment]
輪子復輪子，輪子何其多

**Comment by jokester** [comment]
我这没有精确的更新时间, 加到列表的时间可以git blame看到

每月查询这个有点难..如果你有时间折腾可以提PR (内容或脚本都可以)

**Comment by trim21** [comment]
https://shields.io/category/activity
